### ISSUE TITLE
not working on mac os 10.11 and LO6/LibreOffice Vanilla (from the APPSTORE)

### ISSUE THREAD

**Issue by swhib** [kovleventer/timeStampBackup#7]
Thanks for publishing. This is very useful.

I recommended the version from extensions.libreoffice.org to friends and family who mainly use Linux and Windows. I haven't heard any complaints. But there is one mac user (os 10.11 with LO6 from the appstore) who runs into different problems: 

After installing the LibreOffice crashed (not clear if this is related). After a restart the extension could be used as expected. 

After another restart two different kinds of errors shown on this mac:

    ASIC-Laufzeitfehler.
    Es ist eine Ausnahme aufgetreten
    Type: com.sun.star.task.ErrorCodeIOException
    Message: SfxBaseModel::storeSelf: 0x5032.

When this error occurs the macro window is openend and (if I remember correctly) the line `oDoc.store()` is highlighted. A regular save isn't working either. 

After restarting a different error occurs:

    Es ist eine Ausnahme aufgetreten
    Type: com.sun.star.io.IOException
    Message: SfxBaseModel::impl_store <file:///Users/username/LOBackups//test%20test%20im.%20test_20180401_155017.odt> failed: 0x302.

There are two `//` in the file name. Changing the source code via LibreOffice - Macros and avoiding spaces in the filename didn't help. There is still a similar error report:

    BASIC runtime error.
    An exception occurred 
    Type: com.sun.star.io.IOException
    Message: SfxBaseModel::impl_store <file:///Users/username/LOBackups/test_3_20180401_155523.odt> failed: 0x302.

**Comment by kovleventer** [comment]
This won't be easy to debug for me considering I don't possess currently neither a mac nor a copy of LO6.

The second error impl_store were most likely thrown from https://github.com/LibreOffice/core/blob/master/sfx2/source/doc/sfxbasemodel.cxx#L3026
Reversing the error code from here (https://github.com/LibreOffice/core/blob/62275a93e3b13a20aa1de7945a32a0d25582c1ca/include/vcl/errcode.hxx) I found that the error thrown were possibly this (with all the defined shifting stuff):
#define ERRCODE_IO_NOTEXISTS ErrCode( ErrCodeArea::Io, ErrCodeClass::NotExists, 2 )

That does not solve the problem; it is just my first guess of what the problem might be

**Comment by kovleventer** [comment]
It did work on a newly installed LO6 (on Linux), so this issue is mac-related.
I assume the default backup path variable contains a slash at the end, and so the value of "CreateUnoService("com.sun.star.util.PathSettings").Backup". Can you confirm this? Also does any of the full paths (sDocURL and sBackupURL) contain spaces (for example in the username)?

**Comment by swhib** [comment]
Thanks for the quick reply and thanks for your patience.

I had some more time to experiment and I think I could narrow it down. 

LO6 is not the problem. I use LO6 on my linux and windows machines. 

I just tested on the mac with a current stable version (5.4) from the website. The extension works. Then I downloaded LO6 from the website and the extension also works.

So the problem only occurs if I run LO from the appstore -  https://itunes.apple.com/us/app/libreoffice-vanilla/id921923693?mt=12 . I learned that the appstore on macs uses sandboxing. I manually saved a file in my backup path via the regular file dialog because it is my understanding that this allows this app from the app store to write into this folder in the future. But this didn't help. 

Maybe you could include a warning in the description at https://extensions.libreoffice.org/extensions/timestamp-backup ? Maybe something like "Probably not Working with LibreOffice that is downloaded from the appstore. Detailed bug reports welcome" ?

**Comment by swhib** [comment]
It took me some time to post so I missed your second posting from 6:26pm.

Version 1.16 and 1.17 from the official site work without any modifications on the mac with LO (that is installed from the website): I tested with a filename that contains spaces.

I'll ask a friend on a different machine to try it out. I'll report the results during the week. If an error occurs I will try to post the information you requested.

**Comment by kovleventer** [comment]
Thanks for the help and I updated the extensions page description. About the issue I can't say much, but the error code seems weird, since there are codes for 'ACCESSDENIED' or 'CANTWRITE' defined in errorcode, and these should fit more.

I'll gladly accept any more reports, but I'm not entirely sure this issue can be fixed on this side; so maybe this bug lies in the appstore version of LO.

**Comment by swhib** [comment]
Version 1.1.8 from https://extensions.libreoffice.org works on MacOS 10.11 with LO 6.0.3 (that is NOT from the app store). 

I didn' test with the Vanilla version from the app store because it was still stuck on 5.2 so that I didn't trust the update routine from the appstore for this software.
